"""Deterministic V-pair for skills/comment_classify.py (No-Pure-G invariant).

Covers the one-account premise (authorship by content, never account), the
role-disjoint markers, and the two pre-emptive corrections to dyad-leo's §10
classifier taken from its own open defect report (dyad-leo#63).

Fixtures are literals — the classifier is pure, so no network and no clock.
"""

import hashlib
import re as _re
from pathlib import Path as _Path

from skills import comment_classify
from skills.comment_classify import (
    ROLE_AGENT,
    ROLE_OPERATOR,
    classify_thread,
    comment_role,
    find_violations,
)

CUTOFF = "2026-08-16"
AGENT_HEADER = "**dyad-milo · session:vmnmt5 — agent**"
FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.com/claude-code)_\n"


def c(cid, body, created="2026-08-17T00:00:00Z", **reactions):
    return {"id": cid, "created_at": created, "body": body, "reactions": reactions}


def agent(cid, text="Reported.", created="2026-08-17T00:00:00Z", **reactions):
    return c(cid, f"{AGENT_HEADER}\n\n{text}", created, **reactions)


def operator(cid, text="Do this.", created="2026-08-17T00:00:00Z", **reactions):
    return c(cid, text, created, **reactions)


# --- authorship is read from content, never from the account ----------------

def test_header_marks_agent_authorship():
    assert comment_role(f"{AGENT_HEADER}\n\nbody") == ROLE_AGENT


def test_absent_header_reads_as_operator():
    """Fail-safe direction: unmarked stays in scope rather than silently dropping."""
    assert comment_role("just some words") == ROLE_OPERATOR


def test_header_must_be_the_first_non_empty_line():
    assert comment_role(f"preamble\n{AGENT_HEADER}") == ROLE_OPERATOR


def test_leading_blank_lines_tolerated():
    assert comment_role(f"\n\n{AGENT_HEADER}\n\nbody") == ROLE_AGENT


def test_wrong_dyad_in_header_is_a_violation():
    body = "**dyad-leo · session:xlkg4f — agent**\n\nbody"
    assert any("not 'dyad-milo'" in v for v in find_violations([c(1, body)]))


# --- thread state ------------------------------------------------------------

def test_quiet_thread():
    assert classify_thread([], CUTOFF)["state"] == "quiet"


def test_operator_comment_awaits_the_agent():
    assert classify_thread([operator(1)], CUTOFF)["state"] == "awaiting-agent"


def test_eyes_on_operator_comment_marks_acknowledged():
    assert classify_thread([operator(1, eyes=1)], CUTOFF)["state"] == "acknowledged"


def test_agent_reply_leaves_it_awaiting_the_operator():
    thread = [operator(1, created="2026-08-17T00:00:00Z"),
              agent(2, created="2026-08-17T01:00:00Z")]
    assert classify_thread(thread, CUTOFF)["state"] == "awaiting-operator"


def test_terminal_ack_on_the_agent_comment_closes_the_exchange():
    thread = [operator(1, created="2026-08-17T00:00:00Z"),
              agent(2, created="2026-08-17T01:00:00Z", **{"+1": 1})]
    assert classify_thread(thread, CUTOFF)["state"] == "closed"


def test_thread_is_ordered_by_creation_not_input_order():
    thread = [agent(2, created="2026-08-17T01:00:00Z"),
              operator(1, created="2026-08-17T00:00:00Z")]
    assert classify_thread(thread, CUTOFF)["state"] == "awaiting-operator"


# --- correction 1 (dyad-leo#63): the grandfather cutoff ----------------------

def test_pre_cutoff_comments_are_exempt():
    """Without this, a pre-convention comment reads as unanswered forever."""
    result = classify_thread([operator(1, created="2026-08-06T00:17:16Z")], CUTOFF)
    assert result["state"] == "exempt-pre-convention"
    assert result["pre_cutoff"] == 1


def test_pre_cutoff_comment_does_not_hold_a_live_thread_open():
    thread = [operator(1, created="2026-08-06T00:17:16Z"),
              operator(2, created="2026-08-17T00:00:00Z", eyes=1)]
    result = classify_thread(thread, CUTOFF)
    assert result["state"] == "acknowledged"
    assert result["pre_cutoff"] == 1 and result["operator"] == 1


def test_pre_cutoff_unmarked_agent_comment_is_not_a_violation():
    """Comments predating the convention cannot have obeyed it."""
    body = f"a report{FOOTER}"
    assert find_violations([c(1, body, created="2026-08-06T00:00:00Z")], CUTOFF) == []


# --- correction 2 (dyad-leo#63): the role rule, derived not stored -----------

def test_agent_latest_is_out_of_sweep_scope():
    """§10's gap: 'the classifier has no way to say answered-for-my-role'.

    Derived structurally — an agent-authored latest comment awaits the
    Operator — so no `Awaiting` field is stored and none can go stale.
    """
    assert classify_thread([agent(1)], CUTOFF)["state"] == "awaiting-operator"


def test_agent_latest_is_never_reclassified_by_an_agent_ack():
    thread = [agent(1, created="2026-08-17T00:00:00Z", eyes=1)]
    result = classify_thread(thread, CUTOFF)
    assert result["state"] == "awaiting-operator"
    assert any("agent-authored comment" in v for v in result["violations"])


# --- role-marker violations, decidable without identity ---------------------

def test_unmarked_agent_comment_is_caught_by_its_own_footer():
    """The one shape that proves itself: attribution footer, no header."""
    violations = find_violations([c(1, f"a report{FOOTER}")], CUTOFF)
    assert any("no provenance header" in v for v in violations)


def test_marked_agent_comment_with_footer_is_clean():
    assert find_violations([c(1, f"{AGENT_HEADER}\n\nreport{FOOTER}")], CUTOFF) == []


def test_thumbs_up_on_operator_comment_closes_nothing():
    violations = find_violations([operator(1, **{"+1": 1})], CUTOFF)
    assert any("not a terminal ack" in v for v in violations)


def test_thumbs_up_on_operator_comment_does_not_close_the_thread():
    assert classify_thread([operator(1, **{"+1": 1})], CUTOFF)["state"] == "awaiting-agent"


def test_eyes_on_agent_comment_is_a_role_crossing():
    violations = find_violations([agent(1, eyes=1)], CUTOFF)
    assert any("never of its own" in v for v in violations)


def test_clean_exchange_has_no_violations():
    thread = [operator(1, created="2026-08-17T00:00:00Z", eyes=1),
              agent(2, created="2026-08-17T01:00:00Z", **{"+1": 1})]
    assert classify_thread(thread, CUTOFF)["violations"] == []


# --- provenance: a PASS must say which validator produced it (issue #33) -----

def test_source_stamp_is_hash_of_own_source():
    src = _Path(comment_classify.__file__).read_bytes()
    assert comment_classify.source_stamp() == hashlib.sha256(src).hexdigest()[:12]


def test_source_stamp_shape():
    assert _re.fullmatch(r"[0-9a-f]{12}", comment_classify.source_stamp())


def test_self_test_output_carries_the_stamp(capsys):
    comment_classify.main(["comment_classify.py", "--self-test"])
    out = capsys.readouterr().out
    assert f"comment_classify@{comment_classify.source_stamp()}" in out
