#!/usr/bin/env python3
"""comment_classify — the classifier behind milo's comment-channel conduct.

Single-home for the rules: ``dialectic/comment-protocol.md``. Record: ADR-0021.

**The premise is a constraint, not a feature.** Operator and Agent post from the
same GitHub account, so **identity is never a usable discriminator** — not on
comments, not on reactions. Every marker rides in *content*: a provenance header
for authorship, a role-disjoint emoji for acks. This module is the only place
that reading is implemented, so the rule cannot drift between callers.

What it decides, statelessly, for one issue's thread:

  * which comments are Agent-authored (header present) vs Operator-authored;
  * whether the thread awaits the Agent, awaits the Operator, or is closed;
  * which role-marker violations are present.

Two corrections to dyad-leo's §10 classifier are implemented **pre-emptively**,
from its own open defect report (``dyad-leo#63``, unratified there):

  1. **Grandfather cutoff.** Comments created before the convention existed
     carry no header and would be read as Operator-authored-and-unanswered
     forever. Pre-cutoff comments are exempt.
  2. **Role rule, expressed structurally.** §10's sweep has "no way to say
     'answered-for-my-role'." dyad-leo's proposed fix reads an ``Awaiting``
     field; milo's issues have none, so the same rule is derived instead: **an
     Agent-authored latest comment awaits the Operator** and is out of scope.
     Derived beats stored (craft lesson #16) — there is no field to go stale.

Usage:
  python3 skills/comment_classify.py OWNER/REPO ISSUE_NUMBER   # live, via gh
  python3 skills/comment_classify.py --self-test               # no network
Exit 0 = classified with no violations; exit 1 = violations found.
"""

import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

# The convention's own ratification boundary. Comments created before this are
# exempt from classification (correction 1). Set to the day the convention
# lands; it is a constant, not a stored copy of derivable state — nothing in
# the substrate can answer "when did this rule begin".
CONVENTION_CUTOFF = "2026-08-16"

DYAD = "dyad-milo"

# `**dyad-milo · session:<token> — agent**`, first non-empty line.
HEADER_RE = re.compile(
    r"^\*\*\s*(?P<dyad>[a-z0-9-]+)\s*·\s*session:(?P<session>[A-Za-z0-9._-]+)\s*—\s*agent\s*\*\*\s*$"
)
# The Claude Code attribution footer: strong evidence of Agent authorship even
# when the header is absent. This is what makes "unmarked agent comment" — §10's
# listed refutation — mechanically detectable rather than merely forbidden.
FOOTER_RE = re.compile(r"Generated by \[Claude Code\]|Co-Authored-By:\s*Claude", re.I)

ROLE_AGENT = "agent"
ROLE_OPERATOR = "operator"


def source_stamp():
    """Short content hash of this validator's own source (ADR-0013).

    Duplicated per-linter by design; see the note in ``pgm_lint.source_stamp``.
    """
    return hashlib.sha256(Path(__file__).read_bytes()).hexdigest()[:12]


def first_line(body):
    for line in (body or "").splitlines():
        if line.strip():
            return line.strip()
    return ""


def parse_header(body):
    """Return the header match for an Agent-marked comment, else None."""
    return HEADER_RE.match(first_line(body))


def comment_role(body):
    """Authorship by content, never by account. Absent a header → Operator.

    Fail-safe direction: an unmarked comment reads as Operator-authored, which
    keeps it *in* scope. The opposite default would silently drop the Agent's
    duty to answer.
    """
    return ROLE_AGENT if parse_header(body) else ROLE_OPERATOR


def reaction_count(comment, name):
    return int((comment.get("reactions") or {}).get(name, 0) or 0)


def is_pre_cutoff(comment, cutoff=CONVENTION_CUTOFF):
    created = (comment.get("created_at") or "")[:10]
    return bool(created) and created < cutoff


def find_violations(comments, cutoff=CONVENTION_CUTOFF):
    """Role-marker violations that are decidable without identity."""
    violations = []
    for c in comments:
        ref = f"comment {c.get('id', '?')}"
        role = comment_role(c.get("body", ""))
        header = parse_header(c.get("body", ""))

        if header and header.group("dyad") != DYAD:
            violations.append(
                f"{ref}: provenance header names {header.group('dyad')!r}, not {DYAD!r}")

        # An unmarked comment carrying the Agent's attribution footer is §10's
        # listed refutation, and the one shape that proves itself.
        if not header and FOOTER_RE.search(c.get("body", "")) and not is_pre_cutoff(c, cutoff):
            violations.append(
                f"{ref}: carries the agent attribution footer but no provenance header "
                f"— reads as Operator-authored (unmarked agent comment)")

        # 👀 is the Agent's ack of an *Operator* comment; on an Agent comment it
        # is a role crossing.
        if role == ROLE_AGENT and reaction_count(c, "eyes"):
            violations.append(
                f"{ref}: 'eyes' on an agent-authored comment — 👀 is the agent's ack "
                f"of an Operator comment, never of its own")

        # A 👍 on the Operator's own comment is explicitly not a terminal ack.
        if role == ROLE_OPERATOR and reaction_count(c, "+1"):
            violations.append(
                f"{ref}: '+1' on an Operator-authored comment is not a terminal ack "
                f"(the agent has not acted yet) — it closes nothing")
    return violations


def classify_thread(comments, cutoff=CONVENTION_CUTOFF):
    """Classify one issue's comment thread. Pure — no network, no clock."""
    ordered = sorted(comments, key=lambda c: (c.get("created_at") or "", c.get("id", 0)))
    live = [c for c in ordered if not is_pre_cutoff(c, cutoff)]

    result = {
        "total": len(ordered),
        "pre_cutoff": len(ordered) - len(live),
        "agent": sum(1 for c in live if comment_role(c.get("body", "")) == ROLE_AGENT),
        "operator": sum(1 for c in live if comment_role(c.get("body", "")) == ROLE_OPERATOR),
        "violations": find_violations(ordered, cutoff),
    }

    # A terminal ack: 👍 on an *agent* comment closes the exchange.
    closed = any(
        comment_role(c.get("body", "")) == ROLE_AGENT and reaction_count(c, "+1")
        for c in live)

    if not ordered:
        result["state"] = "quiet"
    elif not live:
        result["state"] = "exempt-pre-convention"
    elif closed:
        result["state"] = "closed"
    else:
        latest = live[-1]
        if comment_role(latest.get("body", "")) == ROLE_AGENT:
            # Correction 2, derived: the agent has spoken last, so the ball is
            # the Operator's. Never the agent's to ack.
            result["state"] = "awaiting-operator"
        elif reaction_count(latest, "eyes"):
            result["state"] = "acknowledged"
        else:
            result["state"] = "awaiting-agent"
    return result


# --- live path -------------------------------------------------------------

def fetch_comments(repo, number):
    out = subprocess.run(
        ["gh", "api", f"repos/{repo}/issues/{number}/comments", "--paginate"],
        capture_output=True, text=True)
    if out.returncode != 0:
        raise RuntimeError(f"gh api failed: {out.stderr.strip()[:200]}")
    return json.loads(out.stdout or "[]")


def main(argv):
    stamp = source_stamp()
    if len(argv) > 1 and argv[1] == "--self-test":
        # Proves the classifier runs without network; the real V-pair is pytest.
        demo = [{"id": 1, "created_at": "2026-08-17T00:00:00Z",
                 "body": "Please look at this.", "reactions": {}}]
        print(json.dumps(classify_thread(demo), indent=2))
        print(f"[COMMENT-CLASSIFY] self-test OK (comment_classify@{stamp})")
        return 0
    if len(argv) < 3:
        print("usage: comment_classify.py OWNER/REPO ISSUE_NUMBER | --self-test")
        return 2
    repo, number = argv[1], argv[2]
    result = classify_thread(fetch_comments(repo, number))
    print(json.dumps(result, indent=2))
    if result["violations"]:
        print(f"[COMMENT-CLASSIFY] FAIL: {repo}#{number} (comment_classify@{stamp}) — "
              f"{len(result['violations'])} violation(s):")
        for v in result["violations"]:
            print(f"  - {v}")
        return 1
    print(f"[COMMENT-CLASSIFY] PASS: {repo}#{number} (comment_classify@{stamp}) "
          f"state={result['state']}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
